- name: "create_cni_plugin_dir"
  become: true
  ansible.builtin.file:
    path: "{{ cni_plugins_path }}"
    state: "directory"

- name: "download_cni_plugins"
  ansible.builtin.get_url:
    url: "{{ cni_plugins_url }}"
    dest: "/tmp/cni-plugins.tgz"
    mode: "600"
  register: "cni_plugins_file"

- name: "unzip_cni_plugins"
  become: true
  ansible.builtin.unarchive:
    remote_src: true
    src: "{{ cni_plugins_file.dest }}"
    dest: "{{ cni_plugins_path }}"
    mode: "0755"

- name: "remove CNI plugins tar file"
  ansible.builtin.file:
    path: "{{ cni_plugins_file.dest }}"
    state: "absent"
